# Generated by Django 2.2.5 on 2019-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_review'),
        ('user_auth', '0003_auto_20190919_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prod',
            field=models.ManyToManyField(blank=True, to='shopping.Product'),
        ),
    ]
