# Generated by Django 2.2.5 on 2019-11-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_profile_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
