# Generated by Django 2.2.5 on 2019-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_auto_20191106_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='no_of_joined',
            field=models.IntegerField(default=0),
        ),
    ]
