# Generated by Django 2.2.5 on 2019-11-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_tournaments_no_of_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingcenters',
            name='contact_details',
            field=models.CharField(default=994989924, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachingcenters',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
