# Generated by Django 2.2.5 on 2019-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_auto_20191106_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachingcenters',
            old_name='address',
            new_name='phone_num',
        ),
        migrations.RemoveField(
            model_name='coachingcenters',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='coachingcenters',
            name='area',
            field=models.CharField(default='vasanth nagar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachingcenters',
            name='pincode',
            field=models.IntegerField(default=533006),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachingcenters',
            name='state',
            field=models.CharField(default='Andhra pradesh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachingcenters',
            name='street_name',
            field=models.CharField(default='gandhi street', max_length=100),
            preserve_default=False,
        ),
    ]
