# Generated by Django 2.2.5 on 2019-11-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_auto_20191106_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingcenters',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
