# Generated by Django 2.2.5 on 2019-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_auto_20191106_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingcenters',
            name='phone_num',
            field=models.BigIntegerField(),
        ),
    ]
