# Generated by Django 2.2.5 on 2019-11-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_auto_20191106_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
