# Generated by Django 2.2.5 on 2019-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_auto_20191108_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingcenters',
            name='image',
            field=models.ImageField(null=True, upload_to='static/sports/Coachingcenters_Images/'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='image',
            field=models.ImageField(null=True, upload_to='static/sports/Tournament_Images/'),
        ),
    ]
