# Generated by Django 2.2.5 on 2019-11-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_auto_20191109_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingcenters',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/sports/Coachingcenters_Images/'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/sports/Tournament_Images/'),
        ),
    ]
