# Generated by Django 2.2.5 on 2019-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_auto_20191110_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_info',
            name='equipment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
