# Generated by Django 2.2.5 on 2019-11-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0016_auto_20191111_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='sport-image'),
        ),
    ]
