# Generated by Django 2.2.5 on 2019-11-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_sport_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/sports/sport-image'),
        ),
    ]
