# Generated by Django 2.2.5 on 2019-11-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_sport_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_info',
            name='playlist',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
