# Generated by Django 2.2.5 on 2019-11-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0020_auto_20191116_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_info',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
