# Generated by Django 2.2.5 on 2019-09-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190921_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastNewsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
