# Generated by Django 2.2.5 on 2019-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_lastnewsupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastnewsupdate',
            name='last_update',
            field=models.CharField(max_length=100),
        ),
    ]
