# Generated by Django 2.2.5 on 2019-09-24 17:45

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190924_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastnewsupdate',
            name='last_update',
            field=django_unixdatetimefield.fields.UnixDateTimeField(),
        ),
    ]
