# Generated by Django 2.2.5 on 2019-11-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190924_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='category',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
