# Generated by Django 2.2.5 on 2019-11-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191108_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
