# Generated by Django 2.2.5 on 2019-11-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredients',
            new_name='description',
        ),
    ]
